.github/workflows/secret-scan.yml

Added GITLEAKS_LICENSE setting on the workflows file.

Update secret-scan.yml to filx build

---

server/mcp_server_vmp/README.md
server/mcp_server_vmp/README_zh.md
server/mcp_server_vmp/pyproject.toml
server/mcp_server_vmp/src/mcp_server_vmp/config.py
server/mcp_server_vmp/src/mcp_server_vmp/server.py
server/mcp_server_vmp/src/mcp_server_vmp/utils.py
server/mcp_server_vmp/src/mcp_server_vmp/vmpapi.py

- fix readme doc error
- fix concurrency bug

fix: fix readme doc error & concurrency bug

---

server/mcp_server_vefaas_sandbox/README.md
server/mcp_server_vefaas_sandbox/src/mcp_server_vefaas_sandbox/server.py

Change-Id: I3fb27ff0a20b21736e3508a01b03450de23fff14

refine: vefaas code sandbox mcp server readme refactor

---

server/mcp_server_certificate_center/README.md
server/mcp_server_certificate_center/README_zh.md

fix: 修复证书中心MCP README

---

server/mcp_server_vod/README.md
server/mcp_server_vod/README_zh.md

Feat mcp vod update

---

server/mcp_server_vefaas_sandbox/README.md

Change-Id: Id0343cc84cd51e64e1bd930b4c600c01593af1ea

docs(README): : add access to the veFaaS Code Sandbox service introduce

---

server/mcp_server_tls/README.md
server/mcp_server_tls/README_zh.md

fixed the subdirectory in tls mcp server configuration.

fix: fixed the subdirectory in tls mcp server configuration

---

server/mcp_server_vefaas_browser/README.md

feat: add veFaaS Browser MCP Server

---

README.md
server/mcp_server_traffic_route/README.md
server/mcp_server_traffic_route/README_zh.md
server/mcp_server_traffic_route/nodejs/src/tools/tr/all.ts
server/mcp_server_traffic_route/nodejs/src/utils/tools.ts
server/mcp_server_traffic_route/python/vcloud/base/aksk.py
server/mcp_server_traffic_route/python/vcloud/base/base_service.py
server/mcp_server_traffic_route/python/vcloud/traffic_route/api/api.py
server/mcp_server_traffic_route/python/vcloud/traffic_route/api/config.py
server/mcp_server_traffic_route/python/vcloud/traffic_route/mcp_server.py
server/mcp_server_traffic_route/python/vcloud/traffic_route/note.py
server/mcp_server_traffic_route/python/vcloud/utils/response.py
server/mcp_server_veen/nodejs/src/utils/tools.ts
server/mcp_server_veen/python/vcloud/base/aksk.py

1. Update TrafficRoute MCP server tools in Python.
2. Move the item TrafficRoute to Enterprise Application in main menu (README of repo home).

Update TrafficRoute MCP

---

server/mcp_server_vefaas_function/src/mcp_server_vefaas_function/vefaas_server.py

enhance veFaaS create_zip_base64 to support multiple file contents && enhance veFaaS tool prompts to improve usability and guidance

feat: enhance veFaaS create_zip_base64 to support multiple file contents

---

server/mcp_server_vefaas_function/src/mcp_server_vefaas_function/vefaas_server.py

fix: enhance vefaas tool prompts

fix: enhance vefaas tool prompts

---

server/mcp_server_vefaas_function/src/mcp_server_vefaas_function/vefaas_server_test.py

fix: add test case for faas create_zip_base64

fix: add test case for faas create_zip_base64

---

server/mcp_server_askecho/README.md

Change-Id: I09617142d8e5e6ac55a52d9a1e3510df8f67cdfa

feat: optimize askecho input

---

server/mcp_server_askecho/README.md

Change-Id: I5c2749a8dbe0cc05035bbc8be536187d1adfdb26

fix: askecho readme

---

server/mcp_server_mongodb/README.md

modify mongodb readme

---

server/mcp_server_vefaas_function/src/mcp_server_vefaas_function/vefaas_server.py

feat(vefaas): update tool description to enforce service uniqueness and gateway reuse

feat(vefaas): update tool description to enforce service uniqueness and gateway reuse

---

server/mcp_server_vefaas_function/src/mcp_server_vefaas_function/sign.py
server/mcp_server_vefaas_function/src/mcp_server_vefaas_function/vefaas_server.py
server/mcp_server_vefaas_function/src/mcp_server_vefaas_function/vefaas_server_test.py

feat(vefaas): support VPC binding on function create/update and auto install dependencies on code upload

feat(vefaas): support VPC binding on function create/update and auto install dependencies on code upload

---

server/mcp_server_billing/pyproject.toml
server/mcp_server_billing/requirements.txt
server/mcp_server_billing/uv.lock
server/mcp_server_cloud_trail/pyproject.toml
server/mcp_server_cloud_trail/requirements.txt
server/mcp_server_cloud_trail/uv.lock
server/mcp_server_cloudidentity/pyproject.toml
server/mcp_server_cloudidentity/requirements.txt
server/mcp_server_cloudidentity/uv.lock
server/mcp_server_iam/pyproject.toml
server/mcp_server_iam/requirements.txt
server/mcp_server_iam/uv.lock
server/mcp_server_organization/pyproject.toml
server/mcp_server_organization/requirements.txt
server/mcp_server_organization/uv.lock
server/mcp_server_project/pyproject.toml
server/mcp_server_project/requirements.txt
server/mcp_server_project/uv.lock
server/mcp_server_resource_share/pyproject.toml
server/mcp_server_resource_share/requirements.txt
server/mcp_server_resource_share/uv.lock
server/mcp_server_resourcecenter/pyproject.toml
server/mcp_server_resourcecenter/requirements.txt
server/mcp_server_resourcecenter/uv.lock
server/mcp_server_sts/pyproject.toml
server/mcp_server_sts/requirements.txt
server/mcp_server_sts/uv.lock
server/mcp_server_tag/pyproject.toml
server/mcp_server_tag/requirements.txt
server/mcp_server_tag/uv.lock

fix: update h11 version

---

server/mcp_server_veapig/pyproject.toml
server/mcp_server_veapig/requirements.txt
server/mcp_server_veapig/src/mcp_server_veapig/main.py
server/mcp_server_veapig/src/mcp_server_veapig/streamable_http.py
server/mcp_server_veapig/src/mcp_server_veapig/veapig_server.py
server/mcp_server_veapig/uv.lock

Veapig fix bug

---

server/mcp_server_vod/src/vevod_mcp/mcp_server.py

remove description when vod cmp init

feat: rm init description

---

server/mcp_server_vedb_mysql/src/mcp_server_vedb_mysql/server.py

vedb:add source tag

---

server/mcp_server_sec_agent/pyproject.toml
server/mcp_server_sec_agent/src/mcp_server_sec_agent/main.py
server/mcp_server_sec_agent/src/mcp_server_sec_agent/server.py
server/mcp_server_sec_agent/uv.lock

2. fix missing tool in stdio mode

1. update mcp version

---

server/mcp_server_askecho/src/mcp_server_askecho/server.py

Change-Id: Icd2f493ed9fe9d088716471c552e3962d090cdf9

feat: add ask_echo mcp init params
